linters:
  enable:
    - dogsled
    - exportloopref
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - misspell
    - nestif
    - prealloc
    - unconvert
    - unparam
    - revive

linters-settings:
  govet:
    enable:
      - fieldalignment


run:
  timeout: 3m

issues:
  exclude-rules:
    - linters:
        - gosec
      text: "G404"
    - linters:
        - funlen
      path: _test\.go
